FROM scratch

WORKDIR /app
COPY amd64/smtprelay /app/
COPY amd64/smtprelay.ini /app/

EXPOSE 25
EXPOSE 465
EXPOSE 587

# Command to run the application
CMD ["./smtprelay", "--config", "smtprelay.ini"]
