FROM alpine
RUN apk add -U --no-cache ca-certificates


FROM scratch
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

WORKDIR /app
COPY arm64/smtprelay /app/
COPY arm64/smtprelay.ini /app/

EXPOSE 25
EXPOSE 465
EXPOSE 587

# Command to run the application
CMD ["./smtprelay", "--config", "smtprelay.ini"]
