FROM scratch

WORKDIR /app
COPY amd64/smtprelay /app/
COPY amd64/smtprelay.ini /app/

# add certs from host
COPY ca-bundle.crt /etc/ssl/certs/ca-bundle.crt
COPY ca-bundle.trust.crt /etc/ssl/certs/ca-bundle.trust.crt 

EXPOSE 25
EXPOSE 465
EXPOSE 587

# Command to run the application
CMD ["./smtprelay", "--config", "smtprelay.ini"]
