name: Build and Push Docker Container

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'  # Run every day

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout original repository
      uses: actions/checkout@v4
      with:
        repository: decke/smtprelay
        path: external_repo
        
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        path: local_repo

    - name: debug
      run: ls

    - name: Setup QEMU for ARM64
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Get current release from container repository
      run: |
        repo_owner="OpenCirclePkgs"
        repo_name="smtprelay"
        package_type="container"
        package_name="smtprelay"

        current_release=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/orgs/$repo_owner/packages/$package_type/$package_name" | jq -r .metadata.container.tags[0].name)

        # Set to empty string if no container exists yet
        current_release=${current_release:-""}

        echo "Current release in the container repository: $current_release"
        
    - name: Check for new releases
      run: |
        latest_release=$(curl -s https://api.github.com/repos/decke/smtprelay/releases/latest | jq -r '.tag_name')
        echo "latest release: $latest_release"

        if [ "$latest_release" != "$current_release" ]; then
          echo "New release found. Building and pushing Docker container..."

          lowercase_repo_name=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')

          ls
          ls local_repo
          ls external_repo
          
          docker buildx create --use
          docker buildx build --no-cache \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/$lowercase_repo_name:$latest_release \
            ./local_repo/

          docker push ghcr.io/$lowercase_repo_name:$latest_release
        else
          echo "No new releases found. Exiting."
        fi
