name: Build and Push Docker Container

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'  # Run every day

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:        
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Get current release from container repository
      id: current
      run: |
        repo_owner="OpenCirclePkgs"
        repo_name="smtprelay"
        package_type="container"
        package_name="smtprelay"

        current_release=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/orgs/$repo_owner/packages/$package_type/$package_name/versions" | jq -r '.[0].metadata.container.tags[0]' | sed 's/-arm64//')

        # Set to empty string if no container exists yet
        current_release=${current_release:-""}

        echo "Current release in the container repository: $current_release"
        echo ""::set-output name=current_release::$current_release""

    - name: Check for new releases
      run: |
        latest_release=$(curl -s https://api.github.com/repos/decke/smtprelay/releases/latest | jq -r '.tag_name')
        echo "latest release: $latest_release"

        if [ "$latest_release" != "${{ steps.current.outputs.current_release }}" ]; then
          echo "New release found. Building and pushing Docker container..."
        else
          echo "No new releases found. Exiting."
          exit 0
        fi

    - name: Setup QEMU for ARM64
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Create Folders
      run: mkdir -p downloaded_files/arm64 & mkdir -p downloaded_files/amd64

    - name: Download files from latest release
      run: |
        latest_release=$(curl -s https://api.github.com/repos/decke/smtprelay/releases/latest | jq -r '.tag_name')
        echo "Latest release: $latest_release"
        
        # Download files from the latest release using the GitHub REST API
        curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -o "smtprelay-$latest_release-linux-arm64.tar.gz" \
        -LO "https://github.com/decke/smtprelay/releases/download/$latest_release/smtprelay-$latest_release-linux-arm64.tar.gz" \
        -LO "https://github.com/decke/smtprelay/releases/download/$latest_release/smtprelay-$latest_release-linux-amd64.tar.gz" \
        -o "smtprelay-$latest_release-linux-amd64.tar.gz"

        tar -xzf smtprelay-$latest_release-linux-arm64.tar.gz -C arm64
        tar -xzf smtprelay-$latest_release-linux-amd64.tar.gz -C amd64

        echo "::set-output name=latest_release::$latest_release"
        lowercase_repo_name=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        echo ""::set-output name=lowercase_repo_name::$lowercase_repo_name""
        
      working-directory: downloaded_files
      id: release

    - name: Build and Push Docker Container (AMD64)
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64
        push: true
        file: Dockerfile-amd64
        context: ./downloaded_files/
        tags: |
          ghcr.io/${{ steps.release.outputs.lowercase_repo_name }}:latest-amd64, ghcr.io/${{ steps.release.outputs.lowercase_repo_name }}:${{ steps.release.outputs.latest_release }}-amd64

    - name: Build and Push Docker Container (ARM64)
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm64
        push: true
        file: Dockerfile-arm64
        context: ./downloaded_files/
        tags: |
          ghcr.io/${{ steps.release.outputs.lowercase_repo_name }}:latest-arm64, ghcr.io/${{ steps.release.outputs.lowercase_repo_name }}:${{ steps.release.outputs.latest_release }}-arm64
